const Ziggy = {
  url: "http://shadcn-admin.test",
  port: null,
  defaults: {},
  routes: {
    "sanctum.csrf-cookie": { uri: "sanctum/csrf-cookie", methods: ["GET", "HEAD"] },
    dashboard: { uri: "dashboard", methods: ["GET", "HEAD"] },
    "dashboard.settings.profile": { uri: "dashboard/settings", methods: ["GET", "HEAD"] },
    "dashboard.settings.profile.update": { uri: "dashboard/settings/profile", methods: ["PATCH"] },
    "dashboard.settings.account": { uri: "dashboard/settings/account", methods: ["GET", "HEAD"] },
    "dashboard.settings.account.update": { uri: "dashboard/settings/account", methods: ["PATCH"] },
    "dashboard.settings.appearance": {
      uri: "dashboard/settings/appearance",
      methods: ["GET", "HEAD"],
    },
    "dashboard.settings.appearance.update": {
      uri: "dashboard/settings/appearance",
      methods: ["PATCH"],
    },
    "dashboard.settings.notifications": {
      uri: "dashboard/settings/notifications",
      methods: ["GET", "HEAD"],
    },
    "dashboard.settings.notifications.update": {
      uri: "dashboard/settings/notifications",
      methods: ["PATCH"],
    },
    "dashboard.settings.display": { uri: "dashboard/settings/display", methods: ["GET", "HEAD"] },
    "dashboard.settings.display.update": { uri: "dashboard/settings/display", methods: ["PATCH"] },
    "dashboard.apps": { uri: "dashboard/apps", methods: ["GET", "HEAD"] },
    "dashboard.chats": { uri: "dashboard/chats", methods: ["GET", "HEAD"] },
    "dashboard.charts": { uri: "dashboard/charts", methods: ["GET", "HEAD"] },
    "dashboard.mail": { uri: "dashboard/mail", methods: ["GET", "HEAD"] },
    "dashboard.tasks": { uri: "dashboard/tasks", methods: ["GET", "HEAD"] },
    "dashboard.users": { uri: "dashboard/users", methods: ["GET", "HEAD"] },
    "profile.edit": { uri: "dashboard/profile", methods: ["GET", "HEAD"] },
    "profile.update": { uri: "dashboard/profile", methods: ["PATCH"] },
    "profile.destroy": { uri: "dashboard/profile", methods: ["DELETE"] },
    "dashboard.coming-soon": { uri: "dashboard/help-center", methods: ["GET", "HEAD"] },
    "dashboard.03": { uri: "dashboard/chat-ai", methods: ["GET", "HEAD"] },
    "dashboard.notifications.index": { uri: "dashboard/notifications", methods: ["GET", "HEAD"] },
    "dashboard.notifications.list": {
      uri: "dashboard/notifications/list",
      methods: ["GET", "HEAD"],
    },
    "dashboard.notifications.unread-count": {
      uri: "dashboard/notifications/unread-count",
      methods: ["GET", "HEAD"],
    },
    "dashboard.notifications.read": {
      uri: "dashboard/notifications/{id}/read",
      methods: ["POST"],
      parameters: ["id"],
    },
    "dashboard.notifications.read-all": {
      uri: "dashboard/notifications/read-all",
      methods: ["POST"],
    },
    "dashboard.notifications.destroy": {
      uri: "dashboard/notifications/{id}",
      methods: ["DELETE"],
      parameters: ["id"],
    },
    "dashboard.notifications.templates.index": {
      uri: "dashboard/notifications/templates",
      methods: ["GET", "HEAD"],
    },
    "dashboard.notifications.templates.create": {
      uri: "dashboard/notifications/templates/create",
      methods: ["GET", "HEAD"],
    },
    "dashboard.notifications.templates.store": {
      uri: "dashboard/notifications/templates",
      methods: ["POST"],
    },
    "dashboard.notifications.templates.show": {
      uri: "dashboard/notifications/templates/{template}",
      methods: ["GET", "HEAD"],
      parameters: ["template"],
      bindings: { template: "id" },
    },
    "dashboard.notifications.templates.edit": {
      uri: "dashboard/notifications/templates/{template}/edit",
      methods: ["GET", "HEAD"],
      parameters: ["template"],
      bindings: { template: "id" },
    },
    "dashboard.notifications.templates.update": {
      uri: "dashboard/notifications/templates/{template}",
      methods: ["PUT", "PATCH"],
      parameters: ["template"],
      bindings: { template: "id" },
    },
    "dashboard.notifications.templates.destroy": {
      uri: "dashboard/notifications/templates/{template}",
      methods: ["DELETE"],
      parameters: ["template"],
      bindings: { template: "id" },
    },
    "dashboard.notifications.templates.toggle-status": {
      uri: "dashboard/notifications/templates/{template}/toggle-status",
      methods: ["POST"],
      parameters: ["template"],
      bindings: { template: "id" },
    },
    "dashboard.notifications.send": {
      uri: "dashboard/notifications/send",
      methods: ["GET", "HEAD"],
    },
    "dashboard.notifications.send.store": {
      uri: "dashboard/notifications/send",
      methods: ["POST"],
    },
    "dashboard.notifications.search-users": {
      uri: "dashboard/notifications/search-users",
      methods: ["GET", "HEAD"],
    },
    register: { uri: "register", methods: ["GET", "HEAD"] },
    login: { uri: "login", methods: ["GET", "HEAD"] },
    "password.request": { uri: "forgot-password", methods: ["GET", "HEAD"] },
    "password.email": { uri: "forgot-password", methods: ["POST"] },
    "password.reset": {
      uri: "reset-password/{token}",
      methods: ["GET", "HEAD"],
      parameters: ["token"],
    },
    "password.store": { uri: "reset-password", methods: ["POST"] },
    "verification.notice": { uri: "verify-email", methods: ["GET", "HEAD"] },
    "verification.verify": {
      uri: "verify-email/{id}/{hash}",
      methods: ["GET", "HEAD"],
      parameters: ["id", "hash"],
    },
    "verification.send": { uri: "email/verification-notification", methods: ["POST"] },
    "password.confirm": { uri: "confirm-password", methods: ["GET", "HEAD"] },
    "password.update": { uri: "password", methods: ["PUT"] },
    logout: { uri: "logout", methods: ["POST"] },
    "dashboard.posts.index": { uri: "dashboard/posts", methods: ["GET", "HEAD"] },
    "dashboard.posts.create": { uri: "dashboard/posts/create", methods: ["GET", "HEAD"] },
    "dashboard.posts.store": { uri: "dashboard/posts", methods: ["POST"] },
    "dashboard.posts.show": {
      uri: "dashboard/posts/{post}",
      methods: ["GET", "HEAD"],
      parameters: ["post"],
      bindings: { post: "slug" },
    },
    "dashboard.posts.edit": {
      uri: "dashboard/posts/{post}/edit",
      methods: ["GET", "HEAD"],
      parameters: ["post"],
      bindings: { post: "slug" },
    },
    "dashboard.posts.update": {
      uri: "dashboard/posts/{post}",
      methods: ["PUT", "PATCH"],
      parameters: ["post"],
      bindings: { post: "slug" },
    },
    "dashboard.posts.destroy": {
      uri: "dashboard/posts/{post}",
      methods: ["DELETE"],
      parameters: ["post"],
      bindings: { post: "slug" },
    },
    "dashboard.categories.index": { uri: "dashboard/categories", methods: ["GET", "HEAD"] },
    "dashboard.categories.create": { uri: "dashboard/categories/create", methods: ["GET", "HEAD"] },
    "dashboard.categories.store": { uri: "dashboard/categories", methods: ["POST"] },
    "dashboard.categories.show": {
      uri: "dashboard/categories/{category}",
      methods: ["GET", "HEAD"],
      parameters: ["category"],
      bindings: { category: "slug" },
    },
    "dashboard.categories.edit": {
      uri: "dashboard/categories/{category}/edit",
      methods: ["GET", "HEAD"],
      parameters: ["category"],
      bindings: { category: "slug" },
    },
    "dashboard.categories.update": {
      uri: "dashboard/categories/{category}",
      methods: ["PUT", "PATCH"],
      parameters: ["category"],
      bindings: { category: "slug" },
    },
    "dashboard.categories.destroy": {
      uri: "dashboard/categories/{category}",
      methods: ["DELETE"],
      parameters: ["category"],
      bindings: { category: "slug" },
    },
    "dashboard.tags.popular": { uri: "dashboard/tags/popular", methods: ["GET", "HEAD"] },
    "dashboard.tags.index": { uri: "dashboard/tags", methods: ["GET", "HEAD"] },
    "dashboard.tags.create": { uri: "dashboard/tags/create", methods: ["GET", "HEAD"] },
    "dashboard.tags.store": { uri: "dashboard/tags", methods: ["POST"] },
    "dashboard.tags.show": {
      uri: "dashboard/tags/{tag}",
      methods: ["GET", "HEAD"],
      parameters: ["tag"],
      bindings: { tag: "slug" },
    },
    "dashboard.tags.edit": {
      uri: "dashboard/tags/{tag}/edit",
      methods: ["GET", "HEAD"],
      parameters: ["tag"],
      bindings: { tag: "slug" },
    },
    "dashboard.tags.update": {
      uri: "dashboard/tags/{tag}",
      methods: ["PUT", "PATCH"],
      parameters: ["tag"],
      bindings: { tag: "slug" },
    },
    "dashboard.tags.destroy": {
      uri: "dashboard/tags/{tag}",
      methods: ["DELETE"],
      parameters: ["tag"],
      bindings: { tag: "slug" },
    },
    "api.products.index": { uri: "api/v1/ecommerce/products", methods: ["GET", "HEAD"] },
    "api.products.store": { uri: "api/v1/ecommerce/products", methods: ["POST"] },
    "api.products.show": {
      uri: "api/v1/ecommerce/products/{product}",
      methods: ["GET", "HEAD"],
      parameters: ["product"],
      bindings: { product: "slug" },
    },
    "api.products.update": {
      uri: "api/v1/ecommerce/products/{product}",
      methods: ["PUT", "PATCH"],
      parameters: ["product"],
      bindings: { product: "slug" },
    },
    "api.products.destroy": {
      uri: "api/v1/ecommerce/products/{product}",
      methods: ["DELETE"],
      parameters: ["product"],
      bindings: { product: "slug" },
    },
    "api.product-categories.index": {
      uri: "api/v1/ecommerce/product-categories",
      methods: ["GET", "HEAD"],
    },
    "api.product-categories.store": {
      uri: "api/v1/ecommerce/product-categories",
      methods: ["POST"],
    },
    "api.product-categories.show": {
      uri: "api/v1/ecommerce/product-categories/{product_category}",
      methods: ["GET", "HEAD"],
      parameters: ["product_category"],
    },
    "api.product-categories.update": {
      uri: "api/v1/ecommerce/product-categories/{product_category}",
      methods: ["PUT", "PATCH"],
      parameters: ["product_category"],
    },
    "api.product-categories.destroy": {
      uri: "api/v1/ecommerce/product-categories/{product_category}",
      methods: ["DELETE"],
      parameters: ["product_category"],
    },
    "api.product-tags.index": { uri: "api/v1/ecommerce/product-tags", methods: ["GET", "HEAD"] },
    "api.product-tags.store": { uri: "api/v1/ecommerce/product-tags", methods: ["POST"] },
    "api.product-tags.show": {
      uri: "api/v1/ecommerce/product-tags/{product_tag}",
      methods: ["GET", "HEAD"],
      parameters: ["product_tag"],
    },
    "api.product-tags.update": {
      uri: "api/v1/ecommerce/product-tags/{product_tag}",
      methods: ["PUT", "PATCH"],
      parameters: ["product_tag"],
    },
    "api.product-tags.destroy": {
      uri: "api/v1/ecommerce/product-tags/{product_tag}",
      methods: ["DELETE"],
      parameters: ["product_tag"],
    },
    "api.orders.index": { uri: "api/v1/ecommerce/orders", methods: ["GET", "HEAD"] },
    "api.orders.store": { uri: "api/v1/ecommerce/orders", methods: ["POST"] },
    "api.orders.show": {
      uri: "api/v1/ecommerce/orders/{order}",
      methods: ["GET", "HEAD"],
      parameters: ["order"],
      bindings: { order: "id" },
    },
    "api.orders.update": {
      uri: "api/v1/ecommerce/orders/{order}",
      methods: ["PUT", "PATCH"],
      parameters: ["order"],
      bindings: { order: "id" },
    },
    "api.orders.destroy": {
      uri: "api/v1/ecommerce/orders/{order}",
      methods: ["DELETE"],
      parameters: ["order"],
      bindings: { order: "id" },
    },
    "api.orders.mark-as-paid": {
      uri: "api/v1/ecommerce/orders/{order}/mark-as-paid",
      methods: ["POST"],
      parameters: ["order"],
      bindings: { order: "id" },
    },
    "api.orders.update-status": {
      uri: "api/v1/ecommerce/orders/{order}/status",
      methods: ["PUT"],
      parameters: ["order"],
      bindings: { order: "id" },
    },
    "dashboard.ecommerce.products.index": {
      uri: "dashboard/ecommerce/products",
      methods: ["GET", "HEAD"],
    },
    "dashboard.ecommerce.products.create": {
      uri: "dashboard/ecommerce/products/create",
      methods: ["GET", "HEAD"],
    },
    "dashboard.ecommerce.products.store": {
      uri: "dashboard/ecommerce/products",
      methods: ["POST"],
    },
    "dashboard.ecommerce.products.show": {
      uri: "dashboard/ecommerce/products/{product}",
      methods: ["GET", "HEAD"],
      parameters: ["product"],
      bindings: { product: "slug" },
    },
    "dashboard.ecommerce.products.edit": {
      uri: "dashboard/ecommerce/products/{product}/edit",
      methods: ["GET", "HEAD"],
      parameters: ["product"],
      bindings: { product: "slug" },
    },
    "dashboard.ecommerce.products.update": {
      uri: "dashboard/ecommerce/products/{product}",
      methods: ["PUT", "PATCH"],
      parameters: ["product"],
      bindings: { product: "slug" },
    },
    "dashboard.ecommerce.products.destroy": {
      uri: "dashboard/ecommerce/products/{product}",
      methods: ["DELETE"],
      parameters: ["product"],
      bindings: { product: "slug" },
    },
    "dashboard.ecommerce.product-categories.index": {
      uri: "dashboard/ecommerce/product-categories",
      methods: ["GET", "HEAD"],
    },
    "dashboard.ecommerce.product-categories.create": {
      uri: "dashboard/ecommerce/product-categories/create",
      methods: ["GET", "HEAD"],
    },
    "dashboard.ecommerce.product-categories.store": {
      uri: "dashboard/ecommerce/product-categories",
      methods: ["POST"],
    },
    "dashboard.ecommerce.product-categories.show": {
      uri: "dashboard/ecommerce/product-categories/{product_category}",
      methods: ["GET", "HEAD"],
      parameters: ["product_category"],
    },
    "dashboard.ecommerce.product-categories.edit": {
      uri: "dashboard/ecommerce/product-categories/{product_category}/edit",
      methods: ["GET", "HEAD"],
      parameters: ["product_category"],
    },
    "dashboard.ecommerce.product-categories.update": {
      uri: "dashboard/ecommerce/product-categories/{product_category}",
      methods: ["PUT", "PATCH"],
      parameters: ["product_category"],
    },
    "dashboard.ecommerce.product-categories.destroy": {
      uri: "dashboard/ecommerce/product-categories/{product_category}",
      methods: ["DELETE"],
      parameters: ["product_category"],
    },
    "dashboard.ecommerce.product-tags.index": {
      uri: "dashboard/ecommerce/product-tags",
      methods: ["GET", "HEAD"],
    },
    "dashboard.ecommerce.product-tags.create": {
      uri: "dashboard/ecommerce/product-tags/create",
      methods: ["GET", "HEAD"],
    },
    "dashboard.ecommerce.product-tags.store": {
      uri: "dashboard/ecommerce/product-tags",
      methods: ["POST"],
    },
    "dashboard.ecommerce.product-tags.show": {
      uri: "dashboard/ecommerce/product-tags/{product_tag}",
      methods: ["GET", "HEAD"],
      parameters: ["product_tag"],
    },
    "dashboard.ecommerce.product-tags.edit": {
      uri: "dashboard/ecommerce/product-tags/{product_tag}/edit",
      methods: ["GET", "HEAD"],
      parameters: ["product_tag"],
    },
    "dashboard.ecommerce.product-tags.update": {
      uri: "dashboard/ecommerce/product-tags/{product_tag}",
      methods: ["PUT", "PATCH"],
      parameters: ["product_tag"],
    },
    "dashboard.ecommerce.product-tags.destroy": {
      uri: "dashboard/ecommerce/product-tags/{product_tag}",
      methods: ["DELETE"],
      parameters: ["product_tag"],
    },
    "dashboard.ecommerce.orders.index": {
      uri: "dashboard/ecommerce/orders",
      methods: ["GET", "HEAD"],
    },
    "dashboard.ecommerce.orders.create": {
      uri: "dashboard/ecommerce/orders/create",
      methods: ["GET", "HEAD"],
    },
    "dashboard.ecommerce.orders.store": { uri: "dashboard/ecommerce/orders", methods: ["POST"] },
    "dashboard.ecommerce.orders.show": {
      uri: "dashboard/ecommerce/orders/{order}",
      methods: ["GET", "HEAD"],
      parameters: ["order"],
      bindings: { order: "id" },
    },
    "dashboard.ecommerce.orders.edit": {
      uri: "dashboard/ecommerce/orders/{order}/edit",
      methods: ["GET", "HEAD"],
      parameters: ["order"],
    },
    "dashboard.ecommerce.orders.update": {
      uri: "dashboard/ecommerce/orders/{order}",
      methods: ["PUT", "PATCH"],
      parameters: ["order"],
      bindings: { order: "id" },
    },
    "dashboard.ecommerce.orders.destroy": {
      uri: "dashboard/ecommerce/orders/{order}",
      methods: ["DELETE"],
      parameters: ["order"],
      bindings: { order: "id" },
    },
    "dashboard.ecommerce.orders.mark-as-paid": {
      uri: "dashboard/ecommerce/orders/{order}/mark-as-paid",
      methods: ["POST"],
      parameters: ["order"],
      bindings: { order: "id" },
    },
    "dashboard.ecommerce.orders.update-status": {
      uri: "dashboard/ecommerce/orders/{order}/status",
      methods: ["PUT"],
      parameters: ["order"],
      bindings: { order: "id" },
    },
    "dashboard.invoices.index": { uri: "dashboard/invoices", methods: ["GET", "HEAD"] },
    "dashboard.invoices.create": { uri: "dashboard/invoices/create", methods: ["GET", "HEAD"] },
    "dashboard.invoices.store": { uri: "dashboard/invoices", methods: ["POST"] },
    "dashboard.invoices.show": {
      uri: "dashboard/invoices/{invoice}",
      methods: ["GET", "HEAD"],
      parameters: ["invoice"],
      bindings: { invoice: "id" },
    },
    "dashboard.invoices.edit": {
      uri: "dashboard/invoices/{invoice}/edit",
      methods: ["GET", "HEAD"],
      parameters: ["invoice"],
      bindings: { invoice: "id" },
    },
    "dashboard.invoices.update": {
      uri: "dashboard/invoices/{invoice}",
      methods: ["PUT", "PATCH"],
      parameters: ["invoice"],
      bindings: { invoice: "id" },
    },
    "dashboard.invoices.destroy": {
      uri: "dashboard/invoices/{invoice}",
      methods: ["DELETE"],
      parameters: ["invoice"],
      bindings: { invoice: "id" },
    },
    "dashboard.invoices.pdf": {
      uri: "dashboard/invoices/{invoice}/pdf",
      methods: ["GET", "HEAD"],
      parameters: ["invoice"],
      bindings: { invoice: "id" },
    },
    "api.api.notifications.index": { uri: "api/v1/notification", methods: ["GET", "HEAD"] },
    "api.api.notifications.recent": { uri: "api/v1/notification/recent", methods: ["GET", "HEAD"] },
    "api.api.notifications.unread-count": {
      uri: "api/v1/notification/unread-count",
      methods: ["GET", "HEAD"],
    },
    "api.api.notifications.mark-all-read": {
      uri: "api/v1/notification/mark-all-read",
      methods: ["POST"],
    },
    "api.api.notifications.destroy-multiple": {
      uri: "api/v1/notification/bulk",
      methods: ["DELETE"],
    },
    "api.api.notifications.show": {
      uri: "api/v1/notification/{notification}",
      methods: ["GET", "HEAD"],
      parameters: ["notification"],
    },
    "api.api.notifications.mark-read": {
      uri: "api/v1/notification/{notification}/mark-read",
      methods: ["POST"],
      parameters: ["notification"],
    },
    "api.api.notifications.mark-unread": {
      uri: "api/v1/notification/{notification}/mark-unread",
      methods: ["POST"],
      parameters: ["notification"],
    },
    "api.api.notifications.destroy": {
      uri: "api/v1/notification/{notification}",
      methods: ["DELETE"],
      parameters: ["notification"],
    },
    "api.api.notifications.templates.toggle-status": {
      uri: "api/v1/notification/templates/{template}/toggle-status",
      methods: ["POST"],
      parameters: ["template"],
      bindings: { template: "id" },
    },
    "api.api.notifications.admin.search-users": {
      uri: "api/v1/notification/admin/users/search",
      methods: ["GET", "HEAD"],
    },
    "api.api.notifications.admin.send": {
      uri: "api/v1/notification/admin/send",
      methods: ["POST"],
    },
    "notification.index": { uri: "notifications", methods: ["GET", "HEAD"] },
    "notification.create": { uri: "notifications/create", methods: ["GET", "HEAD"] },
    "notification.store": { uri: "notifications", methods: ["POST"] },
    "notification.show": {
      uri: "notifications/{notification}",
      methods: ["GET", "HEAD"],
      parameters: ["notification"],
    },
    "notification.edit": {
      uri: "notifications/{notification}/edit",
      methods: ["GET", "HEAD"],
      parameters: ["notification"],
    },
    "notification.update": {
      uri: "notifications/{notification}",
      methods: ["PUT", "PATCH"],
      parameters: ["notification"],
    },
    "notification.destroy": {
      uri: "notifications/{notification}",
      methods: ["DELETE"],
      parameters: ["notification"],
    },
    "dashboard.roles.index": { uri: "dashboard/roles", methods: ["GET", "HEAD"] },
    "dashboard.roles.create": { uri: "dashboard/roles/create", methods: ["GET", "HEAD"] },
    "dashboard.roles.store": { uri: "dashboard/roles", methods: ["POST"] },
    "dashboard.roles.show": {
      uri: "dashboard/roles/{role}",
      methods: ["GET", "HEAD"],
      parameters: ["role"],
      bindings: { role: "id" },
    },
    "dashboard.roles.edit": {
      uri: "dashboard/roles/{role}/edit",
      methods: ["GET", "HEAD"],
      parameters: ["role"],
      bindings: { role: "id" },
    },
    "dashboard.roles.update": {
      uri: "dashboard/roles/{role}",
      methods: ["PUT", "PATCH"],
      parameters: ["role"],
      bindings: { role: "id" },
    },
    "dashboard.roles.destroy": {
      uri: "dashboard/roles/{role}",
      methods: ["DELETE"],
      parameters: ["role"],
      bindings: { role: "id" },
    },
    "dashboard.permissions.index": { uri: "dashboard/permissions", methods: ["GET", "HEAD"] },
    "dashboard.permissions.create": {
      uri: "dashboard/permissions/create",
      methods: ["GET", "HEAD"],
    },
    "dashboard.permissions.store": { uri: "dashboard/permissions", methods: ["POST"] },
    "dashboard.permissions.show": {
      uri: "dashboard/permissions/{permission}",
      methods: ["GET", "HEAD"],
      parameters: ["permission"],
    },
    "dashboard.permissions.edit": {
      uri: "dashboard/permissions/{permission}/edit",
      methods: ["GET", "HEAD"],
      parameters: ["permission"],
      bindings: { permission: "id" },
    },
    "dashboard.permissions.update": {
      uri: "dashboard/permissions/{permission}",
      methods: ["PUT", "PATCH"],
      parameters: ["permission"],
      bindings: { permission: "id" },
    },
    "dashboard.permissions.destroy": {
      uri: "dashboard/permissions/{permission}",
      methods: ["DELETE"],
      parameters: ["permission"],
      bindings: { permission: "id" },
    },
    "dashboard.users.create": { uri: "dashboard/users/create", methods: ["GET", "HEAD"] },
    "dashboard.users.store": { uri: "dashboard/users", methods: ["POST"] },
    "dashboard.users.show": {
      uri: "dashboard/users/{user}",
      methods: ["GET", "HEAD"],
      parameters: ["user"],
      bindings: { user: "id" },
    },
    "dashboard.users.edit": {
      uri: "dashboard/users/{user}/edit",
      methods: ["GET", "HEAD"],
      parameters: ["user"],
      bindings: { user: "id" },
    },
    "dashboard.users.update": {
      uri: "dashboard/users/{user}",
      methods: ["PUT", "PATCH"],
      parameters: ["user"],
      bindings: { user: "id" },
    },
    "dashboard.users.destroy": {
      uri: "dashboard/users/{user}",
      methods: ["DELETE"],
      parameters: ["user"],
      bindings: { user: "id" },
    },
    "dashboard.users.bulk-assign-roles": {
      uri: "dashboard/users/bulk-assign-roles",
      methods: ["POST"],
    },
    "storage.local": {
      uri: "storage/{path}",
      methods: ["GET", "HEAD"],
      wheres: { path: ".*" },
      parameters: ["path"],
    },
  },
};
if (typeof window !== "undefined" && typeof window.Ziggy !== "undefined") {
  Object.assign(Ziggy.routes, window.Ziggy.routes);
}

export { Ziggy };
