/* This file is generated by Ziggy. */
declare module "ziggy-js" {
  interface RouteList {
    "sanctum.csrf-cookie": [];
    dashboard: [];
    "dashboard.settings.profile": [];
    "dashboard.settings.profile.update": [];
    "dashboard.settings.account": [];
    "dashboard.settings.account.update": [];
    "dashboard.settings.appearance": [];
    "dashboard.settings.appearance.update": [];
    "dashboard.settings.notifications": [];
    "dashboard.settings.notifications.update": [];
    "dashboard.settings.display": [];
    "dashboard.settings.display.update": [];
    "dashboard.apps": [];
    "dashboard.chats": [];
    "dashboard.charts": [];
    "dashboard.mail": [];
    "dashboard.tasks": [];
    "dashboard.users": [];
    "profile.edit": [];
    "profile.update": [];
    "profile.destroy": [];
    "dashboard.coming-soon": [];
    "dashboard.03": [];
    "dashboard.notifications.index": [];
    "dashboard.notifications.list": [];
    "dashboard.notifications.unread-count": [];
    "dashboard.notifications.read": [
      {
        name: "id";
        required: true;
      },
    ];
    "dashboard.notifications.read-all": [];
    "dashboard.notifications.destroy": [
      {
        name: "id";
        required: true;
      },
    ];
    "dashboard.notifications.templates.index": [];
    "dashboard.notifications.templates.create": [];
    "dashboard.notifications.templates.store": [];
    "dashboard.notifications.templates.show": [
      {
        name: "template";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.notifications.templates.edit": [
      {
        name: "template";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.notifications.templates.update": [
      {
        name: "template";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.notifications.templates.destroy": [
      {
        name: "template";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.notifications.templates.toggle-status": [
      {
        name: "template";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.notifications.send": [];
    "dashboard.notifications.send.store": [];
    "dashboard.notifications.search-users": [];
    register: [];
    login: [];
    "password.request": [];
    "password.email": [];
    "password.reset": [
      {
        name: "token";
        required: true;
      },
    ];
    "password.store": [];
    "verification.notice": [];
    "verification.verify": [
      {
        name: "id";
        required: true;
      },
      {
        name: "hash";
        required: true;
      },
    ];
    "verification.send": [];
    "password.confirm": [];
    "password.update": [];
    logout: [];
    "dashboard.posts.index": [];
    "dashboard.posts.create": [];
    "dashboard.posts.store": [];
    "dashboard.posts.show": [
      {
        name: "post";
        required: true;
        binding: "slug";
      },
    ];
    "dashboard.posts.edit": [
      {
        name: "post";
        required: true;
        binding: "slug";
      },
    ];
    "dashboard.posts.update": [
      {
        name: "post";
        required: true;
        binding: "slug";
      },
    ];
    "dashboard.posts.destroy": [
      {
        name: "post";
        required: true;
        binding: "slug";
      },
    ];
    "dashboard.categories.index": [];
    "dashboard.categories.create": [];
    "dashboard.categories.store": [];
    "dashboard.categories.show": [
      {
        name: "category";
        required: true;
        binding: "slug";
      },
    ];
    "dashboard.categories.edit": [
      {
        name: "category";
        required: true;
        binding: "slug";
      },
    ];
    "dashboard.categories.update": [
      {
        name: "category";
        required: true;
        binding: "slug";
      },
    ];
    "dashboard.categories.destroy": [
      {
        name: "category";
        required: true;
        binding: "slug";
      },
    ];
    "dashboard.tags.popular": [];
    "dashboard.tags.index": [];
    "dashboard.tags.create": [];
    "dashboard.tags.store": [];
    "dashboard.tags.show": [
      {
        name: "tag";
        required: true;
        binding: "slug";
      },
    ];
    "dashboard.tags.edit": [
      {
        name: "tag";
        required: true;
        binding: "slug";
      },
    ];
    "dashboard.tags.update": [
      {
        name: "tag";
        required: true;
        binding: "slug";
      },
    ];
    "dashboard.tags.destroy": [
      {
        name: "tag";
        required: true;
        binding: "slug";
      },
    ];
    "api.products.index": [];
    "api.products.store": [];
    "api.products.show": [
      {
        name: "product";
        required: true;
        binding: "slug";
      },
    ];
    "api.products.update": [
      {
        name: "product";
        required: true;
        binding: "slug";
      },
    ];
    "api.products.destroy": [
      {
        name: "product";
        required: true;
        binding: "slug";
      },
    ];
    "api.product-categories.index": [];
    "api.product-categories.store": [];
    "api.product-categories.show": [
      {
        name: "product_category";
        required: true;
      },
    ];
    "api.product-categories.update": [
      {
        name: "product_category";
        required: true;
      },
    ];
    "api.product-categories.destroy": [
      {
        name: "product_category";
        required: true;
      },
    ];
    "api.product-tags.index": [];
    "api.product-tags.store": [];
    "api.product-tags.show": [
      {
        name: "product_tag";
        required: true;
      },
    ];
    "api.product-tags.update": [
      {
        name: "product_tag";
        required: true;
      },
    ];
    "api.product-tags.destroy": [
      {
        name: "product_tag";
        required: true;
      },
    ];
    "api.orders.index": [];
    "api.orders.store": [];
    "api.orders.show": [
      {
        name: "order";
        required: true;
        binding: "id";
      },
    ];
    "api.orders.update": [
      {
        name: "order";
        required: true;
        binding: "id";
      },
    ];
    "api.orders.destroy": [
      {
        name: "order";
        required: true;
        binding: "id";
      },
    ];
    "api.orders.mark-as-paid": [
      {
        name: "order";
        required: true;
        binding: "id";
      },
    ];
    "api.orders.update-status": [
      {
        name: "order";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.ecommerce.products.index": [];
    "dashboard.ecommerce.products.create": [];
    "dashboard.ecommerce.products.store": [];
    "dashboard.ecommerce.products.show": [
      {
        name: "product";
        required: true;
        binding: "slug";
      },
    ];
    "dashboard.ecommerce.products.edit": [
      {
        name: "product";
        required: true;
        binding: "slug";
      },
    ];
    "dashboard.ecommerce.products.update": [
      {
        name: "product";
        required: true;
        binding: "slug";
      },
    ];
    "dashboard.ecommerce.products.destroy": [
      {
        name: "product";
        required: true;
        binding: "slug";
      },
    ];
    "dashboard.ecommerce.product-categories.index": [];
    "dashboard.ecommerce.product-categories.create": [];
    "dashboard.ecommerce.product-categories.store": [];
    "dashboard.ecommerce.product-categories.show": [
      {
        name: "product_category";
        required: true;
      },
    ];
    "dashboard.ecommerce.product-categories.edit": [
      {
        name: "product_category";
        required: true;
      },
    ];
    "dashboard.ecommerce.product-categories.update": [
      {
        name: "product_category";
        required: true;
      },
    ];
    "dashboard.ecommerce.product-categories.destroy": [
      {
        name: "product_category";
        required: true;
      },
    ];
    "dashboard.ecommerce.product-tags.index": [];
    "dashboard.ecommerce.product-tags.create": [];
    "dashboard.ecommerce.product-tags.store": [];
    "dashboard.ecommerce.product-tags.show": [
      {
        name: "product_tag";
        required: true;
      },
    ];
    "dashboard.ecommerce.product-tags.edit": [
      {
        name: "product_tag";
        required: true;
      },
    ];
    "dashboard.ecommerce.product-tags.update": [
      {
        name: "product_tag";
        required: true;
      },
    ];
    "dashboard.ecommerce.product-tags.destroy": [
      {
        name: "product_tag";
        required: true;
      },
    ];
    "dashboard.ecommerce.orders.index": [];
    "dashboard.ecommerce.orders.create": [];
    "dashboard.ecommerce.orders.store": [];
    "dashboard.ecommerce.orders.show": [
      {
        name: "order";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.ecommerce.orders.edit": [
      {
        name: "order";
        required: true;
      },
    ];
    "dashboard.ecommerce.orders.update": [
      {
        name: "order";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.ecommerce.orders.destroy": [
      {
        name: "order";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.ecommerce.orders.mark-as-paid": [
      {
        name: "order";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.ecommerce.orders.update-status": [
      {
        name: "order";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.invoices.index": [];
    "dashboard.invoices.create": [];
    "dashboard.invoices.store": [];
    "dashboard.invoices.show": [
      {
        name: "invoice";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.invoices.edit": [
      {
        name: "invoice";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.invoices.update": [
      {
        name: "invoice";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.invoices.destroy": [
      {
        name: "invoice";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.invoices.pdf": [
      {
        name: "invoice";
        required: true;
        binding: "id";
      },
    ];
    "api.api.notifications.index": [];
    "api.api.notifications.recent": [];
    "api.api.notifications.unread-count": [];
    "api.api.notifications.mark-all-read": [];
    "api.api.notifications.destroy-multiple": [];
    "api.api.notifications.show": [
      {
        name: "notification";
        required: true;
      },
    ];
    "api.api.notifications.mark-read": [
      {
        name: "notification";
        required: true;
      },
    ];
    "api.api.notifications.mark-unread": [
      {
        name: "notification";
        required: true;
      },
    ];
    "api.api.notifications.destroy": [
      {
        name: "notification";
        required: true;
      },
    ];
    "api.api.notifications.templates.toggle-status": [
      {
        name: "template";
        required: true;
        binding: "id";
      },
    ];
    "api.api.notifications.admin.search-users": [];
    "api.api.notifications.admin.send": [];
    "notification.index": [];
    "notification.create": [];
    "notification.store": [];
    "notification.show": [
      {
        name: "notification";
        required: true;
      },
    ];
    "notification.edit": [
      {
        name: "notification";
        required: true;
      },
    ];
    "notification.update": [
      {
        name: "notification";
        required: true;
      },
    ];
    "notification.destroy": [
      {
        name: "notification";
        required: true;
      },
    ];
    "dashboard.roles.index": [];
    "dashboard.roles.create": [];
    "dashboard.roles.store": [];
    "dashboard.roles.show": [
      {
        name: "role";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.roles.edit": [
      {
        name: "role";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.roles.update": [
      {
        name: "role";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.roles.destroy": [
      {
        name: "role";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.permissions.index": [];
    "dashboard.permissions.create": [];
    "dashboard.permissions.store": [];
    "dashboard.permissions.show": [
      {
        name: "permission";
        required: true;
      },
    ];
    "dashboard.permissions.edit": [
      {
        name: "permission";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.permissions.update": [
      {
        name: "permission";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.permissions.destroy": [
      {
        name: "permission";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.users.create": [];
    "dashboard.users.store": [];
    "dashboard.users.show": [
      {
        name: "user";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.users.edit": [
      {
        name: "user";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.users.update": [
      {
        name: "user";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.users.destroy": [
      {
        name: "user";
        required: true;
        binding: "id";
      },
    ];
    "dashboard.users.bulk-assign-roles": [];
    "storage.local": [
      {
        name: "path";
        required: true;
      },
    ];
  }
}
export {};
